# 静态文件预览地址
preview-file-ip: 47.109.146.152

file:
  upload-path-resume: files/resume_files/ # TODO 文件上传路径 生产环境下需要修改
  upload-path-avatar: files/avatar_files/
#  upload-path-offers: files/offer_files/
  upload-path-signature: files/signature_files/
  upload-path-material: files/material_files/
  upload-path-enterpriseFile: files/enterprise_files/
  upload-path-offers: files/offer_files/
  upload-path-officeTemplate: files/offer_Template/
#  upload-path-resume: D:/maven/resume_files/ # TODO 文件上传路径 生产环境下需要修改
#  upload-path-avatar: D:/maven/avatar_files/
#  upload-path-offers: D:/maven/offer_files/
#  upload-path-signature: D:/maven/signature_files/
#  upload-path-material: D:/maven/material_files/
#  upload-path-enterpriseFile: D:/maven/enterprise_files/
#  upload-path-office: D:/maven/offer_files/
#  upload-path-officeTemplate: D:/maven/offer_Template/

#pdf:
  # TODO 使用yml配置路径爆错
#  font-path: C:\\Windows\\Fonts\\STXIHEI.TTF
#  registration-path: D:\\maven\\offer_files\\1741588126573_18.pdf

# 服务器配置
server:
  address: 127.0.0.1 # TODO ip地址 后面生产环境需修改以及公司图片等的域名拼接 现在暂时使用ip+port
  port: 8080 # 端口号

#  swagger配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    packageToScan: com.queryx.recruiting_website.controller

# spring配置
spring:
  web:
    resources:
      static-locations:
        - "file:files/"   # 生产环境需要进行修改该参数
#        - "file:D:/maven/"
  application:
    name: recruiting_website

  # 静态资源配置
  servlet:
    multipart:
      enabled: true  # 启用Servlet的多部分文件上传支持
      max-file-size: 4MB  # 设置单个上传文件的最大允许大小
      max-request-size: 100MB  # 设置整个多部分请求的最大允许大小
      file-size-threshold: 0  # 设置文件写入磁盘的大小阈值（0表示文件始终写入磁盘）

  # 数据库配置
  datasource:
    # 数据库连接信息
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCP

# MyBatis Plus配置
mybatis-plus:
  # 该配置指定了MyBatis框架在类路径下查找所有mapper目录下的XML文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # SQL语句等日志信息输出在控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
